Comprehensive_design/Java/dpm/src/com/yuhq/dpm/model/ProjectInfo.java
package com.yuhq.dpm.model;

import java.io.Serializable;
import java.util.Date;

import org.springframework.web.servlet.DispatcherServlet;

/**
 * 项目信息实体
 */
public class ProjectInfo implements Serializable {
	// 项目Id
	private Integer piId;
	// 项目名称
	private String piProjectName;
	// 开始时间
	private Date piStartDate;
	// 结束时间
	private Date piEndDate;
	// 项目状态
	// 1：已申报 2:审核中 3:已通过
	private Integer piStatus;

	public String getStatus() {
		switch (this.piStatus) {
		case 1:
			return "已申报";
		case 2:
			return "审核中";
		default:
			return "已通过";
		}
	}

	@Override
	public String toString() {
		return "ProjectInfo [piId=" + piId + ", piProjectName=" + piProjectName + ", piStartDate=" + piStartDate
				+ ", piEndDate=" + piEndDate + ", piStatus=" + piStatus + "]";
	}

	// alt+shift+s

	public Integer getPiId() {
		return piId;
	}

	public void setPiId(Integer piId) {
		this.piId = piId;
	}

	public String getPiProjectName() {
		return piProjectName;
	}

	public void setPiProjectName(String piProjectName) {
		this.piProjectName = piProjectName;
	}

	public Date getPiStartDate() {
		return piStartDate;
	}

	public void setPiStartDate(Date piStartDate) {
		this.piStartDate = piStartDate;
	}

	public Date getPiEndDate() {
		return piEndDate;
	}

	public void setPiEndDate(Date piEndDate) {
		this.piEndDate = piEndDate;
	}

	public Integer getPiStatus() {
		return piStatus;
	}

	public void setPiStatus(Integer piStatus) {
		this.piStatus = piStatus;
	}

}

Comprehensive_design/Java/dpm/src/com/yuhq/dpm/controller/ProjectInfoController.java
package com.yuhq.dpm.controller;

import java.text.SimpleDateFormat;
import java.util.List;

import javax.annotation.Resource;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;

import com.yuhq.dpm.model.ProjectInfo;
import com.yuhq.dpm.service.ProjectInfoService;

/**
 * 项目信息 控制器
 */
@Controller
@RequestMapping("/projectInfo")
public class ProjectInfoController {

	@Resource
	private ProjectInfoService projectInfoService;

	@RequestMapping("/show")
	public String show(Model model) throws Exception {
		// 查询数据
		List<ProjectInfo> projectInfoList = //
				projectInfoService.findAll();
		// 传递到view视图
		model.addAttribute("projectInfoList", projectInfoList);
		return "projectInfo/show";
	}

	@RequestMapping("/remove")
	public String remove(Integer piId) throws Exception {
		// 删除
		projectInfoService.remove(piId);
		return "redirect:/projectInfo/show";
	}

	@RequestMapping("/save")
	public String save(ProjectInfo projectInfo, String startDate, String endDate) throws Exception {
		SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
		projectInfo.setPiStartDate(sdf.parse(startDate));
		projectInfo.setPiEndDate(sdf.parse(endDate));
		projectInfoService.save(projectInfo);
		return "redirect:/projectInfo/show";
	}

	@RequestMapping("/modify")
	public String modify(ProjectInfo projectInfo, String startDate, String endDate) throws Exception {
		SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
		projectInfo.setPiStartDate(sdf.parse(startDate));
		projectInfo.setPiEndDate(sdf.parse(endDate));
		projectInfoService.modify(projectInfo);
		return "redirect:/projectInfo/show";
	}

	@RequestMapping("/toModify")
	public String toModify(Integer piId, Model model) {
		ProjectInfo projectInfo = projectInfoService.findByPiId(piId);
		model.addAttribute("projectInfo", projectInfo);
		return "projectInfo/modify";
	}

}

Comprehensive_design/Java/dpm/WebContent/index.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>首页</title>
</head>
<body>
	<a href="${pageContext.request.contextPath}/projectInfo/show">显示项目信息列表</a>
</body>
</html>

Comprehensive_design/Java/dpm/WebContent/projectInfo/modify.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>添加数据</title>
</head>
<body>

	<form action="${pageContext.request.contextPath}/projectInfo/modify">
		<input type="hidden" value="${projectInfo.piId }" name="piId">
		项目名称:<input type="text" name="piProjectName"
			value="${projectInfo.piProjectName }"> <br />
		开始时间(yyyy-MM-dd):<input type="text" name="startDate"
			value="<fmt:formatDate value='${projectInfo.piStartDate }'
								pattern="yyyy-MM-dd" />"><br /> 结束时间(yyyy-MM-dd):<input
			type="text" name="endDate" value="<fmt:formatDate value='${projectInfo.piEndDate }'
								pattern="yyyy-MM-dd" />"><br />
		状态: <select name="piStatus">
			<option value="1" ${projectInfo.piStatus==1?"selected":"" }>已申报</option>
			<option value="2"  ${projectInfo.piStatus==2?"selected":"" }>审核中</option>
			<option value="3"  ${projectInfo.piStatus==3?"selected":"" }>已通过</option>
		</select><br /> <input type="submit" value="提交">
	</form>

</body>
</html>

Comprehensive_design/Java/dpm/WebContent/projectInfo/save.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>添加数据</title>
</head>
<body>

<form action="${pageContext.request.contextPath}/projectInfo/save">
	项目名称:<input type="text" name="piProjectName"> <br/>
	开始时间(yyyy-MM-dd):<input type="text" name="startDate"><br/>
	结束时间(yyyy-MM-dd):<input type="text" name="endDate"><br/>
	状态:
		<select name="piStatus">
			<option value="1">已申报</option>
			<option value="2">审核中</option>
			<option value="3">已通过</option>
		</select><br/>
	<input type="submit" value="提交">
</form>

</body>
</html>

Comprehensive_design/Java/dpm/WebContent/projectInfo/show.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>用户信息列表</title>
<style type="text/css">
div {
	width: 800px;
	height: 400px;
	border: 1px solid black;
	margin: 0 auto;
	text-align: center;
}

table {
	width: 100%;
}
</style>
</head>
<body>
	<div>
		<h1>显示用户信息列表</h1>
		<a href="${pageContext.request.contextPath}/projectInfo/save.jsp">添加</a>
		<table border="1">
			<thead>
				<tr>
					<th>项目名称</th>
					<th>开始时间</th>
					<th>结束时间</th>
					<th>状态</th>
					<th>操作</th>
				</tr>
			</thead>
			<tbody>
				<c:forEach var="projectInfo" items="${projectInfoList }">
					<tr>
						<td>${projectInfo.piProjectName }</td>
						<td><fmt:formatDate value="${projectInfo.piStartDate }"
								pattern="yyyy-MM-dd HH:mm:ss" /></td>
						<td><fmt:formatDate value="${projectInfo.piEndDate }"
								pattern="yyyy-MM-dd HH:mm:ss" /></td>
						<td>${projectInfo.status }</td>
						<td>
							<a href="${pageContext.request.contextPath}/projectInfo/toModify?piId=${projectInfo.piId}">更新</a>
							<a href="${pageContext.request.contextPath}/projectInfo/remove?piId=${projectInfo.piId}">删除</a>
						</td>
					</tr>
				</c:forEach>
			</tbody>
		</table>
	</div>
</body>
</html>